spring:
  application:
    name: biosamples-search
  elasticsearch:
    username: elastic
    password: elastic
    uris: http://localhost:9200
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
management:
  endpoints:
    web:
      exposure:
        include: metrics,health



