spring:
  application:
    name: biosamples-search
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
biosamples:
  search:
    indexing:
      fixed-rate: 60




